name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies with composer
      run: composer install -o -n --prefer-dist
    - name: Test everything
      run: vendor/bin/phpunit --testdox
